# Generated by Django 2.2.2 on 2019-06-11 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='orgnizationalinformation',
            name='privacy_policy',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='orgnizationalinformation',
            name='alt_contact_no',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='orgnizationalinformation',
            name='slogan',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
