# Generated by Django 2.1.7 on 2019-06-19 04:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0003_subscriber'),
        ('newsapp', '0003_auto_20190617_1607'),
    ]

    operations = [
    ]
