# Generated by Django 2.2.2 on 2019-06-30 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0004_merge_20190619_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='newsapp.Admin'),
        ),
    ]
