# Generated by Django 2.2.2 on 2019-07-01 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0006_auto_20190701_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
    ]
