# Generated by Django 2.2.2 on 2019-07-01 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0007_news_is_verified'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
    ]
