# Generated by Django 2.2.2 on 2019-07-01 14:55

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0009_news_active'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('verified', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='active',
        ),
    ]
