# Generated by Django 2.2.2 on 2019-07-01 15:06

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0011_auto_20190701_2041'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
                ('verified', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RemoveField(
            model_name='news',
            name='active',
        ),
    ]
