# Generated by Django 2.2.2 on 2019-07-02 06:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0012_auto_20190701_2051'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='sub_category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='newsapp.NewsSubCategory'),
        ),
    ]
