# Generated by Django 2.2.2 on 2019-07-02 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0013_auto_20190702_1229'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='news',
            managers=[
            ],
        ),
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
