# Generated by Django 2.2.3 on 2019-07-04 04:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0015_auto_20190704_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/admin/'),
        ),
        migrations.AlterField(
            model_name='editor',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='news/editor/'),
        ),
    ]
