# Generated by Django 2.2.3 on 2019-07-18 06:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0019_auto_20190704_1056'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admin',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='editor',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='orgnizationalinformation',
            name='contact_no',
            field=models.CharField(max_length=15),
        ),
    ]
