# Generated by Django 2.2.2 on 2019-07-18 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('newsapp', '0020_auto_20190718_1209'),
        ('newsapp', '0020_contact'),
    ]

    operations = [
    ]
